Add and Remove Branch
iankiema/Todo-list-webpack pull request #2
Opened 2023-07-20 14:56 UTC by iankiema

The following files have being updated:
-Src folder
-Dist folder

2023-07-20 16:26 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @iankiema👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️

- [ ] It's a webpack project and should run on a live server but I can't see any script in the `package.json` file to run the development server, Please add the script to start the dev server.

- [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-20 16:26 UTC, thecodechaser commented on src/index.js
> +const taskInput = document.getElementById('task-input');
- [ ] Please don't disable the linter instead fix them manually. It will help you to write more clean and professional code.

2023-07-20 16:26 UTC, thecodechaser commented on src/index.js
> +    });
- [ ] Please move all code of this project to a new JavaScript file as requested in the project requirements.

![image](https://github.com/iankiema/Todo-list-webpack/assets/83803414/6272ae56-a23b-4275-9657-7fae25e355cb)

2023-07-20 16:26 UTC, thecodechaser commented on src/index.js
> +
- [ ] Please make sure deleting a task should update all remaining items' indexes, so they represent the current list order and are unique(i.e. if you're deleting the first task index 1 from the list, the index of the next task(2) should set to 1). Currently, It's not updating the index on deleting a task.

![image](https://github.com/iankiema/Todo-list-webpack/assets/83803414/8ae325dd-bd8e-447e-87d2-02de6e49b8c8)

2023-07-20 16:26 UTC, thecodechaser commented on src/index.js
> +  };
- [ ] Please make sure By default new tasks should have the property index set to the value of the new array length (i.e. if you're adding a 6th task to the list, the index of that task should equal to 6). Currently, It's not working. You can see the duplicate indexes in the below screenshot.

![image](https://github.com/iankiema/Todo-list-webpack/assets/83803414/d51eef90-b87b-41b0-8b60-e498e8a37deb)

2023-07-21 19:50 UTC, Strangeal approved these changes
Hi @iankiema, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/JoSiL3L4ON8DlyVxv0/giphy.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-21 20:01 UTC, merged